### ISSUE TITLE
unable to boot if wrong image is flashed

### ISSUE THREAD

**Issue by fiplistener** [paolosabatino/multitool#1]
My box is a rk3228b marked as a rk3229. If I flash an image meant for the rk3229 to the emmc I can't boot multitool anymore. I think it's because it's trying to use a device tree for the rk3229 but I'm not sure. It would be nice to have some clarification about what to do in this situation. Thank you.

**Comment by paolosabatino** [comment]
Hello, this is not really an issue of the multitool but more about the image you flashed.
If you flashed an armbian image, please write in the forum here: https://forum.armbian.com/topic/12656-csc-armbian-for-rk322x-tv-boxes/

BTW, rk3228b and rk3229 are mostly the same chip, with minor differences. It happens that on some board the DDR memory is not correctly recognized and causes the board to "brick". That's why the installation procedure (on the forum thread first page) suggests to try first the image on an sdcard rather than doing a straightforward installation on eMMC.
